spring.application.name=maharecruitment-parent
server.port=8777

spring.profiles.active=local

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update


server.servlet.context-path=/MahaitRecruitment

# Disable Thymeleaf cache (optional)
spring.thymeleaf.cache=false


# Maximum file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.springframework.transaction=DEBUG

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# =========================
# SMS Gateway Configuration
# =========================
sms.api.url=https://api.smsprovider.com/send
sms.api.key=${SMS_API_KEY}
sms.sender-id=GOVMH


# =========================
# Email Gateway Configuration
# =========================

# add these new properties
spring.mail.transport.protocol=smtp
spring.mail.from.email=sudhirshahare.egov@gmail.com

# modify these properties with your credentials

# configuration email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sudhirshahare.egov@gmail.com
spring.mail.password=yjnv ywqb mmoh mgql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false 
