#spring.datasource.url=jdbc:postgresql://10.0.1.193:5432/mahaitrecritment1
spring.datasource.url=jdbc:postgresql://10.0.1.193:5432/Test
#spring.datasource.url=jdbc:postgresql://localhost:5432/maharecruitment

spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=Mahait
spring.jpa.show-sql=true