spring.datasource.url=jdbc:postgresql://10.0.0.208:5432/mahaitrecritment1
#spring.datasource.url=jdbc:postgresql://10.0.1.193:5432/mahaitrecruitment

spring.datasource.username=postgres
spring.datasource.password=mahait
spring.jpa.show-sql=true
